### Test 1
POST http://localhost:1234/api/v1/profile
content-type: application/json

{
    "AccountName": "PintoGamer64",
    "realName": "Joan Sebastian Cardozo Salinas",
    "mail": "test1234@gmail.com",
    "password": "test1234"
}
### 
POST https://steamclonai.onrender.com/api/v1/profile
content-type: application/json

{
    "status": "Offline",
    "profileName": "jose",
    "AccountName": "jose51",
    "realName": "jose alveira",
    "vacStatus": 1,
    "mail": "jose51@gmail.com",
    "theme": 1,
    "profilePicture": 1,
    "backgroundImage": 1,
    "password": "jose51"
}
### Test 2
GET http://localhost:1234/api/v1/profile/724b47d2-c6d0-4581-8620-60dc4203806e

### Test 2.5 Get Public Library
GET http://localhost:1234/api/v1/profile/bf1f7936-c98f-4714-bb53-50dbb6d52fe0/games

### Test 3 - Make a Friend
POST http://localhost:1234/api/v1/profile/bf1f7936-c98f-4714-bb53-50dbb6d52fe0
content-type: application/json

{
    "From": "e3722ea6-0dec-4b78-8fe8-4ede8ad0ef0a"
}

### Test 3 - Make a Friend to Another

POST http://localhost:1234/api/v1/profile/e3722ea6-0dec-4b78-8fe8-4ede8ad0ef0a
content-type: application/json

{
    "From": "0f14ce24-fff7-42de-a664-1e5d2af3520d"
}

### Test 4 - Comment an Account
POST http://localhost:1234/api/v1/profile/0f14ce24-fff7-42de-a664-1e5d2af3520d/comment
content-type: application/json

{
    "publicId": "bf1f7936-c98f-4714-bb53-50dbb6d52fe0",
	"content": "XDDDDD"
}

### Test 5 - Response To Friend Request
POST http://localhost:1234/api/v1/profile/bf1f7936-c98f-4714-bb53-50dbb6d52fe0/confirmation
content-type: application/json

{
    "responseFriend": true,
    "publicId": "e3722ea6-0dec-4b78-8fe8-4ede8ad0ef0a"
}

### Test 5 - Response To Friend Request to Another
POST http://localhost:1234/api/v1/profile/e3722ea6-0dec-4b78-8fe8-4ede8ad0ef0a/confirmation
content-type: application/json

{
    "responseFriend": true,
    "publicId": "0f14ce24-fff7-42de-a664-1e5d2af3520d"
}

### Test 3 - Login

PUT http://localhost:1234/api/v1/profile/login
content-type: application/json

{
    "mail": "jose51@gmail.com", 
    "password": "jose51"
}

### Tes 4 -> Rage
POST http://localhost:1234/api/v1/profile/verify
content-type: application/json

{
    "Token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdGF0dXMiOjQwNCwiaWF0IjoxNzIyNTMwOTY2LCJleHAiOjE3MjMxMzU3NjZ9.X1cLEUwqNGUzWMnLJxI9oT8umIarrejcklYRroOt4nQ"
}